### ISSUE TITLE
Project Diablo II Request: Add charms of +5 and +10 for ease of checking

### ISSUE THREAD

**Issue by Endarire** [BetweenWalls/portal#3]
Greetings, @BetweenWalls!

For the sake of convenience, may we also get the option of adding charms of +5 skills and +10 skills to the +1 skills and +20 skills?  This way, we can easily compute real world values for skill bonuses.

Thankee!

**Comment by chadam189** [comment]
I like this idea, I created a quick PR for it:

https://github.com/BetweenWalls/portal/pull/4

**Comment by BetweenWalls** [comment]
Implemented
